@startuml state_verify_in-toto_link

[*] --> EndpointCalled : Calls verify_in-toto_link endpoint
EndpointCalled --> SavedLinkFile : Save uploaded link file
SavedLinkFile --> VerifyLinkFile : Verify .link file

VerifyLinkFile --> VerificationSuccess : [success]
VerifyLinkFile --> InvalidSignature : [failure]
VerifyLinkFile --> LayoutExpired : [failure]
VerifyLinkFile --> LinkNotFound : [failure]
VerifyLinkFile --> ThresholdNotMet : [failure]
VerifyLinkFile --> ArtifactRuleViolation :[failure]
VerifyLinkFile --> LayoutFileMissing : [failure]
VerifyLinkFile --> LayoutVerificationError : [failure]

VerificationSuccess --> [*]
InvalidSignature --> [*]
LayoutExpired --> [*]
LinkNotFound --> [*]
ThresholdNotMet --> [*]
ArtifactRuleViolation --> [*]
LayoutFileMissing --> [*]
LayoutVerificationError --> [*]

@enduml

