@startuml state_verify_bom_and_link

[*] --> EndpointCalled : Cals verify_bom_and_link endpoint
EndpointCalled --> SavedBOMFile : Save uploaded BOM file[success]
EndpointCalled --> FileSaveError : Save uploaded BOM file[failure]

SavedBOMFile --> ValidatedBOM : Validate BOM against schema[success]
SavedBOMFile --> BOMInvalid : Validate BOM against schema[failure]
ValidatedBOM --> VerifiedSignature : Extract and verify BOM signature[success]
ValidatedBOM --> SignatureInvalid : Extract and verify BOM signature[failure]
VerifiedSignature --> ExtractedLinkReference : Extract .link file reference[success]
VerifiedSignature --> LinkReferenceMissing : Extract .link file reference[failure]
ExtractedLinkReference --> DownloadedFromMinIO : Download .link file from MinIO[success]
ExtractedLinkReference --> MinIODownloadError : Download .link file from MinIO[failure]
DownloadedFromMinIO --> VerifyLinkFile : Start verifying .link file

VerifyLinkFile --> VerificationSuccess : [success]
VerifyLinkFile --> InvalidSignature : [failure]
VerifyLinkFile --> LayoutExpired : [failure]
VerifyLinkFile --> LinkNotFound : [failure]
VerifyLinkFile --> ThresholdNotMet : [failure]
VerifyLinkFile --> ArtifactRuleViolation :[failure]
VerifyLinkFile --> LayoutFileMissing : [failure]
VerifyLinkFile --> LayoutVerificationError : [failure]

FileSaveError --> [*]
BOMInvalid --> [*]
SignatureInvalid --> [*]
LinkReferenceMissing --> [*]
MinIODownloadError --> [*]


VerificationSuccess --> [*]
InvalidSignature --> [*]
LayoutExpired --> [*]
LinkNotFound --> [*]
ThresholdNotMet --> [*]
ArtifactRuleViolation --> [*]
LayoutFileMissing --> [*]
LayoutVerificationError --> [*]



@enduml