@startuml usecase

left to right direction
skinparam linetype straight
actor "AI Developer" as Developer
actor "AI User or Verifier" as User

note "The AI developer makes his AIBOM \npublic for users to verify." as Note
Developer .up. Note
Note .up. User


'(Prepare Input Files) as PrepareInputs
'(Defines a model.keras file) as ModelFile
'(Defines a dataset.csv file) as DatasetFile
'(Defines a datasetdefinition.yaml file) as DatasetDefinitionFile

'Developer --> PrepareInputs
'Developer --> ModelFile
'Developer --> DatasetFile
'Developer --> DatasetDefinitionFile
'PrepareInputs ..> ModelFile : <<include>>
'PrepareInputs ..> DatasetFile : <<include>>
'PrepareInputs ..> DatasetDefinitionFile : <<include>>


rectangle "AIBoMGen System" as AIBoMGenSystem {
    
    (Request Training Status) as RequestStatus
    (Retrieve Artifacts) as RetrieveArtifacts
    (Retrieve CycloneDX AIBOM) as RetrieveAIBOM
    (Submit Training Job and Generate AIBOM) as SubmitJob

    (Verify CycloneDX AIBOM) as VerifyAIBOM
    (Verify Artifacts) as VerifyArtifacts
    (Verify In-Toto Link) as VerifyInTotoLink
}
Developer --> RetrieveArtifacts

Developer --> SubmitJob
Developer --> RequestStatus
Developer --> RetrieveAIBOM
RetrieveArtifacts ..> RetrieveAIBOM : <<include>>


User --> VerifyAIBOM
User --> VerifyArtifacts
User --> VerifyInTotoLink

'SubmitJob ..> PrepareInputs : <<include>>
VerifyAIBOM ..> VerifyInTotoLink : <<include>>

note left of User : This actor can be anyone who \nwants to verify the integrity and \nauthentication of the AIBOM and its artifacts.



@enduml