@startuml verifier_sequence

actor "AI User or Verifier" as verifier

participant "Web API" as webAPI
database "Minio object storage" as minioStorage

autonumber 1.1
group Verify AIBOM
verifier ->> webAPI: Verify AIBOM
activate webAPI
webAPI -> webAPI: Check AIBOM Signature validity
webAPI -> minioStorage: Get referenced In-toto link
activate minioStorage
minioStorage --> webAPI: In-toto link
deactivate minioStorage
webAPI -> webAPI: Verify In-toto link
webAPI --> verifier: Verification result
deactivate webAPI
end

autonumber inc A
group Verify Only In-toto Link
verifier ->> webAPI: Verify only In-toto link
activate webAPI
webAPI -> minioStorage: Get In-toto link
activate minioStorage
minioStorage --> webAPI: In-toto link
deactivate minioStorage
webAPI -> webAPI: Verify In-toto link
webAPI --> verifier: Verification result
deactivate webAPI
end

autonumber inc A
group Verify File Upload
verifier ->> webAPI: Verify file-upload
activate webAPI
webAPI -> minioStorage: Get In-toto link
activate minioStorage
minioStorage --> webAPI: In-toto link
deactivate minioStorage
webAPI -> webAPI: Compare file hash with AIBOM and/or In-toto link
webAPI --> verifier: Verification result
deactivate webAPI
end

autonumber inc A
group Verify MinIO Artifacts
verifier ->> webAPI: Verify MinIO artifacts
activate webAPI
webAPI -> minioStorage: Get In-toto link
activate minioStorage
minioStorage --> webAPI: In-toto link
deactivate minioStorage
webAPI -> webAPI: Compare hashes with In-toto link
webAPI --> verifier: Verification result
deactivate webAPI
end

@enduml